# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learn__nlp',
                'doc_host': 'https://giordafrancis.github.io',
                'git_url': 'https://github.com/giordafrancis/learn__nlp',
                'lib_path': 'learn__nlp'},
  'syms': {'learn__nlp.core': {'learn__nlp.core.foo': ('core.html#foo', 'learn__nlp/core.py')}}}
